import { motion } from 'framer-motion';
import { ArrowRight, CheckCircle2, Clock, ShieldCheck, Sparkles, UserRoundCheck } from 'lucide-react';
import { useState } from 'react';
import { Layout } from './components/Layout';
import { categories } from './data/categories';
import { AuthProvider, useAuth } from './hooks/useAuth';
import { LanguageProvider, useLanguage } from './i18n/LanguageContext';
import { login, signup } from './services/authService';
import { createImpactRecord, listMyImpactRecords, listPendingImpactRecords, listPublicImpactRecords, reviewImpactRecord } from './services/impactService';
import type { ImpactCategory, ImpactRecord, Visibility } from './types';

type Page = 'home'|'about'|'actions'|'rules'|'impact'|'login'|'signup'|'dashboard'|'record'|'profile'|'admin'|'privacy'|'terms'|'contact';
const fade = { initial: { opacity: 0, y: 18 }, animate: { opacity: 1, y: 0 }, transition: { duration: .45 } };
function Shell() { const [page, setPage] = useState<Page>('home'); return <Layout page={page} setPage={setPage}><Router page={page} setPage={setPage}/></Layout>; }
function Router({ page, setPage }: { page: Page; setPage: (page: Page) => void }) {
  if (page==='home') return <Home setPage={setPage}/>; if (page==='actions') return <Actions/>; if (page==='impact') return <Impact/>; if (page==='rules') return <Rules/>; if (page==='about') return <About/>; if (page==='login') return <AuthScreen mode="login" setPage={setPage}/>; if (page==='signup') return <AuthScreen mode="signup" setPage={setPage}/>; if (page==='dashboard') return <Dashboard setPage={setPage}/>; if (page==='record') return <RecordImpact setPage={setPage}/>; if (page==='admin') return <Admin/>; return <SimplePage page={page}/>;
}
function Section({ children, className='' }: { children: React.ReactNode; className?: string }) { return <section className={`mx-auto max-w-7xl px-4 py-16 ${className}`}>{children}</section>; }
function Home({ setPage }: { setPage: (p: Page) => void }) { const { t, lang } = useLanguage(); return <><Section className="py-20"><div className="grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><motion.div {...fade}><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-sm font-bold text-emerald-200"><Sparkles size={16}/> Privacy-first community impact</div><h1 className="max-w-4xl text-5xl font-extrabold tracking-tight text-white md:text-7xl">{t('tagline')}.</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-slate-300">{t('heroText')}</p><div className="mt-8 flex flex-wrap gap-3"><button className="btn-primary" onClick={() => setPage('record')}>{t('recordImpact')}<ArrowRight size={18}/></button><button className="btn-soft" onClick={() => setPage('impact')}>{t('exploreCommunity')}</button></div></motion.div><motion.div {...fade} className="glass rounded-[2rem] p-6"><div className="grid gap-4 sm:grid-cols-2"><Metric title={lang==='ar'?'أثر مسجل':'Actions Recorded'} value="12,458"/><Metric title={lang==='ar'?'مدينة':'Cities'} value="41"/><Metric title={lang==='ar'?'مجالات خدمة':'Categories'} value="18"/><Metric title={lang==='ar'?'مراجعة آمنة':'Safe Review'} value="97%"/></div><div className="mt-5 rounded-3xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-slate-300">{lang==='ar'?'شخص في أبوظبي ساعد كبير سن اليوم — بدون كشف أي بيانات شخصية.':'Someone in Abu Dhabi helped a senior today — without exposing personal details.'}</p></div></motion.div></div></Section><Section><Title title={lang==='ar'?'كيف يعمل؟':'How it works'} text={lang==='ar'?'ثلاث خطوات بسيطة تحافظ على الثقة والخصوصية.':'Three simple steps designed around trust and privacy.'}/><div className="grid gap-4 md:grid-cols-3"><Step icon={<UserRoundCheck/>} title={t('record')} text="Submit a positive action with safe city-level context."/><Step icon={<ShieldCheck/>} title={t('review')} text="Moderators review suspicious or sensitive records."/><Step icon={<CheckCircle2/>} title={t('visibleImpact')} text="Approved actions increase personal and community impact."/></div></Section></>; }
function Metric({ title, value }: { title: string; value: string }) { return <div className="card p-5"><div className="text-3xl font-extrabold text-white">{value}</div><div className="mt-1 text-sm text-slate-400">{title}</div></div>; }
function Step({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="card p-6"><div className="mb-4 inline-flex rounded-2xl bg-emerald-400/10 p-3 text-emerald-300">{icon}</div><h3 className="text-xl font-bold text-white">{title}</h3><p className="mt-2 text-slate-400">{text}</p></div>; }
function Title({ title, text }: { title: string; text: string }) { return <div className="mb-8"><h2 className="text-3xl font-extrabold text-white md:text-4xl">{title}</h2><p className="mt-3 max-w-2xl text-slate-400">{text}</p></div>; }
function Actions() { const { lang } = useLanguage(); return <Section><Title title={lang==='ar'?'مجالات الأثر':'Impact Categories'} text={lang==='ar'?'قوالب واضحة تساعد المستخدم على التسجيل بدون كشف بيانات حساسة.':'Guided categories help users record safer, clearer impact.'}/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map(c=>{const Icon=c.icon; return <div key={c.id} className="card p-6"><div className={`mb-5 inline-flex rounded-2xl bg-gradient-to-br ${c.color} p-3 text-white`}><Icon/></div><h3 className="text-xl font-bold">{lang==='ar'?c.ar:c.en}</h3><p className="mt-2 text-sm text-slate-400">{lang==='ar'?'سجل أثرًا مختصرًا وآمنًا بدون بيانات شخصية حساسة.':'Record concise, safe impact without sensitive personal data.'}</p></div>})}</div></Section>; }
function Impact() { const { lang } = useLanguage(); return <Section><Title title={lang==='ar'?'الأثر المجتمعي':'Community Impact'} text={lang==='ar'?'صفحة عامة مجهولة الهوية لا تشبه شبكات التواصل ولا تعرض بيانات شخصية.':'An anonymous-first public impact view, not a social feed.'}/><PublicFeed/></Section>; }
function PublicFeed() { const [records,setRecords]=useState<ImpactRecord[]>([]); const [loaded,setLoaded]=useState(false); const { lang }=useLanguage(); if(!loaded){setLoaded(true); listPublicImpactRecords().then(setRecords).catch(()=>setRecords([]));} return <div className="grid gap-4">{records.length===0 ? <div className="card p-6 text-slate-300">{lang==='ar'?'لا توجد سجلات عامة بعد. بعد إعداد Firebase واعتماد الأفعال ستظهر هنا.':'No public records yet. After Firebase setup and approval, records will appear here.'}</div> : records.map(r=><ImpactCard key={r.id} record={r}/>)}</div>; }
function ImpactCard({ record }: { record: ImpactRecord }) { return <div className="card p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-bold text-white">{record.title}</h3><p className="mt-1 text-sm text-slate-400">{record.city}, {record.countryCode} · {record.visibility==='public_profile'?record.userDisplayName:'Someone'}</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">Approved</span></div></div>; }
function Rules() { const { lang }=useLanguage(); const rules=lang==='ar'?['لا تشارك بيانات شخصية حساسة.','لا تستخدم عناوين دقيقة.','الأثر لا يظهر كمعتمد قبل المراجعة.','النقاط رمزية وليست وعدًا ماليًا.','أي محاولة احتيال قد تؤدي لتعليق الحساب.']:['Do not share sensitive personal data.','Do not use precise addresses.','Impact records are reviewed before approval.','Impact score is symbolic, not financial.','Abuse or spam can lead to suspension.']; return <Section><Title title={lang==='ar'?'قواعد الثقة':'Trust Rules'} text={lang==='ar'?'القواعد مصممة لحماية المستخدمين ومنع التفاخر أو الاحتيال.':'Rules are designed to protect users and prevent abuse.'}/><div className="grid gap-3">{rules.map(r=><div className="card flex gap-3 p-5" key={r}><CheckCircle2 className="text-emerald-300"/><span>{r}</span></div>)}</div></Section>; }
function About() { const { lang }=useLanguage(); return <Section><Title title={lang==='ar'?'عن AidiCore':'About AidiCore'} text={lang==='ar'?'AidiCore منصة أثر مجتمعي تحافظ على الخصوصية والثقة.':'AidiCore is a privacy-first community impact platform.'}/><div className="card p-7 text-lg leading-8 text-slate-300">{lang==='ar'?'نحن لا نبني شبكة اجتماعية للتفاخر، بل سجل أثر آمن يساعد الأفراد والمؤسسات على قياس الخير بطريقة محترمة وقابلة للتوسع.':'We are not building a social network for showing off. We are building a safer impact registry that helps people and organizations measure positive actions respectfully.'}</div></Section>; }
function AuthScreen({ mode, setPage }: { mode: 'login'|'signup'; setPage: (p: Page)=>void }) { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const { lang }=useLanguage(); const submit=async(e:React.FormEvent)=>{e.preventDefault(); setError(''); try{ if(mode==='login') await login(email,password); else await signup(email,password,name||email.split('@')[0]); setPage('dashboard'); }catch(err){setError(err instanceof Error?err.message:'Authentication failed');}}; return <Section className="max-w-xl"><div className="glass rounded-[2rem] p-8"><h1 className="text-3xl font-extrabold">{mode==='login'?(lang==='ar'?'تسجيل الدخول':'Login'):(lang==='ar'?'حساب جديد':'Create account')}</h1><form onSubmit={submit} className="mt-6 grid gap-4">{mode==='signup'&&<input className="input" placeholder={lang==='ar'?'الاسم':'Display name'} value={name} onChange={e=>setName(e.target.value)}/>}<input className="input" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="input" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<p className="text-sm text-red-300">{error}</p>}<button className="btn-primary justify-center" type="submit">{mode==='login'?'Login':'Sign up'}</button><button type="button" className="text-sm text-slate-400" onClick={()=>setPage(mode==='login'?'signup':'login')}>{mode==='login'?'Need an account? Sign up':'Already have an account? Login'}</button></form></div></Section>; }
function Dashboard({ setPage }: { setPage:(p:Page)=>void }) { const { appUser, firebaseUser }=useAuth(); const { lang }=useLanguage(); if(!firebaseUser) return <RequireLogin setPage={setPage}/>; return <Section><Title title={lang==='ar'?'لوحة الأثر':'Impact Dashboard'} text={`${lang==='ar'?'مرحبًا':'Welcome'}, ${appUser?.displayName || firebaseUser.email}`}/><div className="grid gap-4 md:grid-cols-4"><Metric title="Impact Score" value={String(appUser?.impactScore||0)}/><Metric title="Approved" value={String(appUser?.approvedActions||0)}/><Metric title="Pending" value="—"/><Metric title="Categories" value="—"/></div><div className="mt-8 flex gap-3"><button className="btn-primary" onClick={()=>setPage('record')}>{lang==='ar'?'سجّل أثرًا':'Record Impact'}</button><button className="btn-soft" onClick={()=>setPage('profile')}>{lang==='ar'?'الملف الشخصي':'Profile'}</button></div><MyRecords/></Section>; }
function MyRecords(){ const { firebaseUser }=useAuth(); const [records,setRecords]=useState<ImpactRecord[]>([]); const [loaded,setLoaded]=useState(false); if(firebaseUser&&!loaded){setLoaded(true); listMyImpactRecords(firebaseUser.uid).then(setRecords).catch(()=>setRecords([]));} return <div className="mt-8 grid gap-3">{records.map(r=><ImpactCard key={r.id} record={r}/>)}</div> }
function RequireLogin({ setPage }: { setPage:(p:Page)=>void }){ return <Section><div className="card p-8"><h2 className="text-2xl font-bold">Login required</h2><p className="mt-2 text-slate-400">Please login to continue.</p><button className="btn-primary mt-5" onClick={()=>setPage('login')}>Login</button></div></Section> }
function RecordImpact({ setPage }: { setPage:(p:Page)=>void }) { const { firebaseUser, appUser }=useAuth(); const { lang }=useLanguage(); const [form,setForm]=useState({title:'',category:'community_service' as ImpactCategory,details:'',occurredAt:new Date().toISOString().slice(0,10),countryCode:'AE',city:'',visibility:'anonymous_public' as Visibility}); const [done,setDone]=useState(false); if(!firebaseUser) return <RequireLogin setPage={setPage}/>; const submit=async(e:React.FormEvent)=>{e.preventDefault(); await createImpactRecord({ ...form, userId: firebaseUser.uid, userDisplayName: appUser?.displayName || firebaseUser.email || 'User' }); setDone(true);}; return <Section className="max-w-3xl"><Title title={lang==='ar'?'سجّل أثرًا إيجابيًا':'Record Impact'} text={lang==='ar'?'اكتب وصفًا آمنًا بدون أرقام هواتف أو عناوين دقيقة.':'Write a safe description without phone numbers or precise addresses.'}/>{done?<div className="card p-8"><CheckCircle2 className="text-emerald-300"/><h2 className="mt-3 text-2xl font-bold">{lang==='ar'?'تم الإرسال للمراجعة':'Submitted for review'}</h2></div>:<form onSubmit={submit} className="card grid gap-4 p-6"><input className="input" placeholder={lang==='ar'?'العنوان':'Title'} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><select className="input" value={form.category} onChange={e=>setForm({...form,category:e.target.value as ImpactCategory})}>{categories.map(c=><option key={c.id} value={c.id}>{lang==='ar'?c.ar:c.en}</option>)}</select><textarea className="input min-h-32" placeholder={lang==='ar'?'التفاصيل الآمنة':'Safe details'} value={form.details} onChange={e=>setForm({...form,details:e.target.value})} required/><div className="grid gap-4 md:grid-cols-3"><input className="input" type="date" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/><input className="input" placeholder="Country" value={form.countryCode} onChange={e=>setForm({...form,countryCode:e.target.value})}/><input className="input" placeholder={lang==='ar'?'المدينة':'City'} value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div><select className="input" value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value as Visibility})}><option value="private">{lang==='ar'?'خاص':'Private'}</option><option value="anonymous_public">{lang==='ar'?'عام بدون اسم':'Anonymous public'}</option><option value="public_profile">{lang==='ar'?'عام باسم المستخدم':'Public profile'}</option></select><button className="btn-primary justify-center">{lang==='ar'?'إرسال للمراجعة':'Submit for review'}</button></form>}</Section>; }
function Admin(){ const { isAdmin, firebaseUser }=useAuth(); const [records,setRecords]=useState<ImpactRecord[]>([]); const [loaded,setLoaded]=useState(false); const { lang }=useLanguage(); if(!isAdmin) return <Section><div className="card p-8">Admin access required.</div></Section>; if(!loaded){setLoaded(true); listPendingImpactRecords().then(setRecords).catch(()=>setRecords([]));} const review=async(r:ImpactRecord,status:'approved'|'rejected')=>{await reviewImpactRecord(r.id,status,firebaseUser!.uid,status); setRecords(records.filter(x=>x.id!==r.id));}; return <Section><Title title={lang==='ar'?'لوحة الإدارة':'Admin Console'} text={lang==='ar'?'مراجعة الأثر، الاحتيال، والملاحظات.':'Review queue, fraud score and audit notes.'}/><div className="grid gap-4">{records.length===0?<div className="card p-6 text-slate-300">No pending records.</div>:records.map(r=><div key={r.id} className="card p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-bold">{r.title}</h3><p className="text-sm text-slate-400">{r.city} · Fraud {r.fraudScore}/100 · {r.auditRequired?'Audit required':'Standard'}</p></div><div className="flex gap-2"><button className="btn-soft !py-2" onClick={()=>review(r,'rejected')}>Reject</button><button className="btn-primary !py-2" onClick={()=>review(r,'approved')}>Approve</button></div></div><p className="mt-3 text-sm text-slate-300">{r.details}</p></div>)}</div></Section> }
function SimplePage({page}:{page:Page}){return <Section><Title title={page.toUpperCase()} text="This page is prepared in the AidiCore V1 route map."/><div className="card p-6 text-slate-300">Content-ready page placeholder for V1 documentation and legal content.</div></Section>}
export default function App(){ return <LanguageProvider><AuthProvider><Shell/></AuthProvider></LanguageProvider>; }
